version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
    networks: 
        - app-networks

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: cendekiaone
      MYSQL_DATABASE: db_cendekiaone
      MYSQL_USER: cendekiaone
      MYSQL_PASSWORD: cendekiaone
    ports:
      - "3301:3306"
    networks: 
        - app-networks
networks:
    app-networks:
        driver: bridge